print('--TABUADA MULTIPLICAÇÃO--')
n=int(input('Digite um número: '))
print(10*'--')
print(f'{n} x 1 = {n*1}')
print(f'{n} x 2 = {n*2}')
print(f'{n} x 3 = {n*3}')
print(f'{n} x 4 = {n*4}')
print(f'{n} x 5 = {n*5}')
print(f'{n} x 6 = {n*6}')
print(10*'--')