print('--CONVERSOR DE MEDIDAS--')
m=float(input('Digite uma distância em metros: '))
print(10*'--')
print(f'Sua distância em km é: {m/1000}')
print(f'Sua distância em hm é: {m/100}')
print(f'Sua distância em dam é: {m/10}')
print(f'Sua distância em dm é: {m*10}')
print(f'Sua distância em cm é: {m*100}')
print(f'Sua distância em mm é: {m*1000}')