print('--DISSECANDO--')
a=input('Digite algo: ')
print(10*'--')
print(type(a))
print(f'Só espaços? {a.isspace()}')
print(f'É número? {a.isnumeric()}')
print(f'É alfabetico? {a.isalpha()}')
print(f'É alfanúmericpo? {a.isalnum()}')
print(f'Está em maiúsculas? {a.isupper()}')
print(f'Está em minúsculas? {a.islower()}')
print(f'Está captalizada? {a.istitle()}')