print('--CALCULADORA DOBRO, TRIPLO E RAIZ QUADRADA--')
n=int(input('Digite um número: '))
print(10*'--')
print(f'O dobro do seu número é: {n*2}')
print(f'O triplo do seu número é: {n*3}')
print(f'A raiz quadrada do seu número é: {n**1/2:.2f}')